[package]
name = "drc20-driver"
version.workspace = true
edition.workspace = true
license.workspace = true

description = "Data driver for the DRC20 reference contract"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
dusk-data-driver = { workspace = true }
drc20-types = { path = "../types", features = ["serde"] }

[features]
ffi = ["dusk-data-driver/wasm-export"]
js = ["ffi", "dusk-data-driver/alloc"]
